language: cpp
sudo: false

compiler:
  - clang
  - gcc

os:
  - linux
  - osx

matrix:
  fast_finish: true
  
addons:
  apt:
    sources: 
      - llvm-toolchain-precise-3.7
      - george-edison55-precise-backports
      - ubuntu-toolchain-r-test
    packages:
      - clang-3.7
      - g++-5
      - gcc-5
      - cmake
      - cmake-data
      - libluajit-5.1-dev
      - liblua5.1-0-dev
      - libpthread-stubs0-dev
      - libgl1-mesa-dev
      - xorg-dev
      - libfreetype6-dev
      - libopenal-dev
git:
  submodules: false

before_install:
  - git submodule update --init glfw

install:
  - cmake --version
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update ; brew install llvm freetype lua luajit openal-soft;brew outdated gcc || brew upgrade gcc ; brew outdated cmake || brew upgrade cmake ; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" -a "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" -a "$CXX" = "clang++" ]; then export CXX="clang++-3.7" CC="clang-3.7"; fi
  - mkdir deps && cd deps
  - curl -L -O https://github.com/g-truc/glm/releases/download/0.9.7.4/glm-0.9.7.4.zip && unzip glm-0.9.7.4.zip
  - export GLM_ROOT_DIR=$(pwd)/glm
  - curl -O -L https://github.com/g-truc/gli/releases/download/0.8.1.0/gli-0.8.1.0.zip && unzip gli-0.8.1.0.zip
  - export GLI_ROOT_DIR=$(pwd)/gli
  - git clone https://github.com/miloyip/rapidjson.git
  - export RAPIDJSON_ROOT_DIR=$(pwd)/rapidjson
  - git clone https://github.com/libRocket/libRocket.git
  - cd libRocket/Build 
  - cmake -DCMAKE_INSTALL_PREFIX=.. -DBUILD_LUA_BINDINGS=TRUE -DBUILD_UNIVERSAL_BINARIES=OFF
  - make install -j2 && cd ../..
  - export ROCKET_ROOT=$(pwd)/libRocket
  - touch cache
  - cd ..

before_script:
  - mkdir build
  - cd build
  - cmake ..

script: make -j2
cache:
  apt: true

notifications:
  slack: byteforge-team:kisF1nc1JVGxnVtGQ4notBAG
