language: cpp
sudo: required
dist: trusty

compiler:
  - clang
  - gcc

os:
  - linux
  - osx

matrix:
  fast_finish: true
  
addons:
  apt:
    sources: 
      - george-edison55-precise-backports
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.7
    packages:
      - libboost1.54-dev
      - libboost-filesystem1.54-dev
      - clang-3.7
      - g++-5
      - gcc-5
      - cmake
      - cmake-data
      - libluajit-5.1-dev
      - libpthread-stubs0-dev
      - libgl1-mesa-dev
      - xorg-dev
      - libfreetype6-dev
      - libopenal-dev
git:
  submodules: false

before_install:
  - git submodule update --init glfw
  - git submodule update --init spark
  - cd ./spark
  - git submodule update --init deps/nanovg
  - git submodule update --init deps/pugixml
  - cd ..

install:
  - cmake --version
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update ; brew install boost llvm freetype lua luajit openal-soft;brew outdated gcc || brew upgrade gcc ; brew outdated cmake || brew upgrade cmake ; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" -a "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" -a "$CXX" = "clang++" ]; then export CXX="clang++-3.7" CC="clang-3.7"; fi
  - mkdir deps && cd deps
  - git clone https://github.com/g-truc/glm.git
  - export GLM_ROOT_DIR=$(pwd)/glm
  - git clone https://github.com/g-truc/gli.git
  - export GLI_ROOT_DIR=$(pwd)/gli
  - git clone https://github.com/miloyip/rapidjson.git
  - export RAPIDJSON_ROOT_DIR=$(pwd)/rapidjson
  - git clone https://github.com/libRocket/libRocket.git
  - cd ..

before_script:
  - mkdir build
  - cd build
  - cmake ..

script: make -j2
cache:
  apt: true

notifications:
  slack: byteforge-team:kisF1nc1JVGxnVtGQ4notBAG
