language: cpp

compiler:
  - gcc

addons:
  apt:
    sources:
      - george-edison55-precise-backports
    packages:
      - cmake
      - cmake-data
      
git:
  submodules: false

before_script:
  - mkdir build
  - cd build
  - cmake ..

script: make
