language: cpp

compiler:
  - gcc

addons:
  apt:
    sources:
      - george-edison55-precise-backports
    packages:
      - cmake
      - cmake-data
      - libluajit-5.1-dev
      - libsfml-dev
      - libopenal-dev
      - libglm-dev
git:
  submodules: false

before_script:
  - mkdir build
  - cd build
  - cmake ..

script: make
