language: cpp
dist: trusty
sudo: false

compiler:
  - clang
  - gcc

os:
  - linux

addons:
  apt:
    sources: 
      - llvm-toolchain-precise-3.7
      - george-edison55-precise-backports
      - ubuntu-toolchain-r-test
    packages:
      - clang-3.7
      - g++-5
      - gcc-5
      - cmake
      - cmake-data
      - libluajit-5.1-dev
      - liblua5.1-0-dev
      - libpthread-stubs0-dev
      - libgl1-mesa-dev
      - libx11-dev
      - libx11-xcb-dev
      - libxcb-image0-dev
      - libxrandr-dev
      - libxcb-randr0-dev
      - libudev-dev
      - libfreetype6-dev
      - libopenal-dev
      - libvorbis-dev
      - libogg-dev
      - libflac-dev
git:
  submodules: false

install:
  - cmake --version
  - if [ "$TRAVIS_OS_NAME" = "linux" -a "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" -a "$CXX" = "clang++" ]; then export CXX="clang++-3.7" CC="clang-3.7"; fi
  - if ![ -d deps ]; then mkdir deps; fi
  - cd deps
  - if ![ -d deps ]; then wget http://www.sfml-dev.org/files/SFML-2.3.2-sources.zip; fi
  - if ![ -d deps ]; then unzip -q SFML-2.3.2-sources.zip; fi
  - if ![ -d deps ]; then cd SFML-2.3.2 && mkdir build && cd build && cmake -DCMAKE_INSTALL_PREFIX=.. .. && make install -j2 && cd ../..; fi
  - export SFML_ROOT=$(pwd)/SFML-2.3.2
  - if ![ -d deps ]; then git clone https://github.com/g-truc/glm.git ; fi
  - export GLM_ROOT_DIR=$(pwd)/glm
  - if ![ -d deps ]; then git clone https://github.com/g-truc/gli.git ; fi
  - export GLI_ROOT_DIR=$(pwd)/gli
  - if ![ -d deps ]; then git clone https://github.com/miloyip/rapidjson.git ; fi
  - export RAPIDJSON_ROOT_DIR=$(pwd)/rapidjson
  - if ![ -d deps ]; then git clone https://github.com/libRocket/libRocket.git ; fi
  - if ![ -d deps ]; then cd libRocket/Build ; fi
  - if ![ -d deps ]; then cmake -DCMAKE_INSTALL_PREFIX=.. -DBUILD_LUA_BINDINGS=TRUE ; fi
  - if ![ -d deps ]; then make install -j2 && cd ../.. ; fi
  - if ![ -d deps ]; then echo "Built librocket" ; fi
  - export ROCKET_ROOT=$(pwd)/libRocket
  - cd ..

before_script:
  - mkdir build
  - cd build
  - cmake ..

script: make
cache:
  apt: true
  directories:
  - deps
