language: cpp
dist: trusty

compiler:
  - clang
  - gcc

os:
  - linux
  - osx

addons:
  apt:
    sources: 
      - llvm-toolchain-precise-3.7
      - george-edison55-precise-backports
      - ubuntu-toolchain-r-test
    packages:
      - clang-3.7
      - g++-5
      - gcc-5
      - cmake
      - cmake-data
      - libluajit-5.1-dev
      - liblua5.1-0-dev
      - libopenal-dev
      - libfreetype6-dev
      - libx11-dev
      - libxcb1
      - libx11-xcb-dev
      - libxcb-randr0
      - libxcb-image0
      - libgl1-mesa-dev
      - libudev1
git:
  submodules: false

install:
  - cmake --version
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update ; brew install llvm freetype sfml lua luajit;brew outdated gcc || brew upgrade gcc ; brew outdated cmake || brew upgrade cmake ; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" -a "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" -a "$CXX" = "clang++" ]; then export CXX="clang++-3.7" CC="clang-3.7"; fi
  - mkdir deps
  - cd deps
  - wget http://www.sfml-dev.org/files/SFML-2.3.2-sources.zip
  - unzip -q SFML-2.3.2-sources.zip
  - cd SFML-2.3.2 && mkdir build && cd build && cmake -DCMAKE_INSTALL_PREFIX=.. .. && make install -j2 && cd ../..
  - export SFML_ROOT=$(pwd)/SFML-2.3.2
  - git clone https://github.com/g-truc/glm.git
  - export GLM_ROOT_DIR=$(pwd)/glm
  - git clone https://github.com/g-truc/gli.git 
  - export GLI_ROOT_DIR=$(pwd)/gli
  - git clone https://github.com/miloyip/rapidjson.git
  - export RAPIDJSON_ROOT_DIR=$(pwd)/rapidjson
  - git clone https://github.com/libRocket/libRocket.git
  - cd libRocket/Build 
  - cmake -DCMAKE_INSTALL_PREFIX=.. -DBUILD_LUA_BINDINGS=TRUE 
  - make install -j2 && cd ../..
  - echo "Built librocket"
  - export ROCKET_ROOT=$(pwd)/libRocket
  - cd ..

before_script:
  - mkdir build
  - cd build
  - cmake ..

script: make
