language: cpp

compiler:
  - gcc

addons:
  apt:
    sources:
      - george-edison55-precise-backports
    packages:
      - cmake
      - cmake-data
      - libluajit-5.1-dev
      - libsfml-dev
      - libopenal-dev
      - libglm-dev
      - libfreetype6-dev
git:
  submodules: false

install:
  - mkdir deps
  - cd deps
  - git clone https://github.com/g-truc/gli.git 
  - export GLI_ROOT_DIR=$(pwd)/gli
  - git clone https://github.com/miloyip/rapidjson.git
  - export RAPIDJSON_ROOT_DIR=$(pwd)/rapidjson
  - git clone https://github.com/libRocket/libRocket.git
  - cd libRocket && cd Build && cmake . && sudo make install && cd ...
  - cd ..

before_script:
  - mkdir build
  - cd build
  - cmake ..

script: make
