language: cpp
dist: trusty

compiler:
  - gcc

addons:
  apt:
    sources: 
      - ubuntu-toolchain-r-test
    packages:
      - cmake
      - cmake-data
      - libluajit-5.1-dev
      - liblua5.1-0-dev
      - libopenal-dev
      - libfreetype6-dev
      - libx11-dev
      - libxcb1
      - libx11-xcb-dev
      - libxcb-randr0
      - libxcb-image0
      - libgl1-mesa-dev
      - libudev1
      - gcc-4.9
      - g++-4.9
git:
  submodules: false

install:
  - cmake --version
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.9" CC="gcc-4.9"; fi
  - mkdir deps
  - cd deps
  - wget --no-check-certificate http://www.sfml-dev.org/files/SFML-2.3.2-linux-gcc-64-bit.tar.gz && tar -zxvf SFML-2.3.2-linux-gcc-64-bit.tar.gz
  - export SFML_ROOT=$(pwd)/SFML-2.3.2
  - git clone https://github.com/g-truc/glm.git
  - export GLM_ROOT_DIR=$(pwd)/glm
  - git clone https://github.com/g-truc/gli.git 
  - export GLI_ROOT_DIR=$(pwd)/gli
  - git clone https://github.com/miloyip/rapidjson.git
  - export RAPIDJSON_ROOT_DIR=$(pwd)/rapidjson
  - git clone https://github.com/libRocket/libRocket.git
  - cd libRocket/Build 
  - cmake -DCMAKE_INSTALL_PREFIX=.. -DBUILD_LUA_BINDINGS=TRUE 
  - make install -j2 && cd ../..
  - echo "Built librocket"
  - export ROCKET_ROOT=$(pwd)/libRocket
  - cd ..

before_script:
  - mkdir build
  - cd build
  - cmake ..

script: make
