language: cpp

compiler:
  - gcc

addons:
  apt:
    sources:
      - george-edison55-precise-backports
    packages:
      - cmake
      - cmake-data
      - libluajit-5.1-dev
      - libsfml-dev
      - libopenal-dev
      - libglm-dev
      - libfreetype6-dev
git:
  submodules: false

install:
  - mkdir deps
  - cd deps
  - git clone https://github.com/g-truc/gli.git 
  - cd gli && cmake . && make install && cd ..

before_script:
  - mkdir build
  - cd build
  - cmake ..

script: make
