platform:
    - Win32
    - x64

configuration:
  - Debug
  - Release

install:
  - cmake --version
  - md deps
  - cd deps
  - git clone https://github.com/g-truc/glm.git
  - set GLM_ROOT_DIR=%CD%/glm
  - git clone https://github.com/g-truc/gli.git
  - set GLI_ROOT_DIR=%CD%/gli
  - git clone https://github.com/miloyip/rapidjson.git
  - set RAPIDJSON_ROOT_DIR=%CD%/rapidjson
  - curl http://download.savannah.gnu.org/releases/freetype/ft263.zip
  - 7z e ft263.zip
  - cd ./freetype-2.6.3/
  - md Build
  - cd Build
  - cmake ..
  - msbuild ALL_BUILD.vcxproj
  - cd ../../
  - git clone https://github.com/libRocket/libRocket.git
  - cd libRocket/Build 
  - cmake -DCMAKE_INSTALL_PREFIX=.. -DBUILD_LUA_BINDINGS=TRUE -DBUILD_UNIVERSAL_BINARIES=OFF
  - make install -j2 && cd ../..
  - set ROCKET_ROOT=%CD%/libRocket
  - cd ..

matrix:
  fast_finish: true

notifications:
- provider: Slack
  incoming_webhook: https://hooks.slack.com/services/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
  channel: '#general'
  on_build_success: true
  on_build_failure: true