platform:
    - Win32
    - x64

configuration:
  - Release

build:
  parallel: true 

init:
- ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

on_finish:
- ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

install:
  - cmake --version
  - md deps
  - cd deps
  - git clone https://github.com/g-truc/glm.git
  - set GLM_ROOT_DIR=%CD%/glm
  - git clone https://github.com/g-truc/gli.git
  - set GLI_ROOT_DIR=%CD%/gli
  - git clone https://github.com/miloyip/rapidjson.git
  - set RAPIDJSON_ROOT_DIR=%CD%/rapidjson
  - curl -L -o freetype.tar.bz2 http://download.savannah.gnu.org/releases/freetype/freetype-2.6.3.tar.bz2
  - tar xvfj ./freetype.tar.bz2
  - cd ./freetype-2.6.3/
  - md Build
  - cd Build
  - cmake .. -DCMAKE_INSTALL_PREFIX=../../freetype/
  - msbuild INSTALL.vcxproj /property:Configuration=Release 
  - cd ../../
  - git clone https://github.com/Byte-Forge/luajit.git
  - git clone https://github.com/libRocket/libRocket.git
  - cd libRocket/Build 
  - cmake -DCMAKE_INSTALL_PREFIX=.. 
    -DBUILD_LUA_BINDINGS=TRUE -DLUA_LIBRARY="${CMAKE_CURRENT_SOURCE_DIR}/../../luajit/lib/%PLATFORM%/lua51.lib" 
    -DLUA_INCLUDE_DIR="${CMAKE_CURRENT_SOURCE_DIR}/../../luajit/include" 
    -DFREETYPE_LIBRARY="${CMAKE_CURRENT_SOURCE_DIR}/../../freetype/lib/freetype.lib"  
    -DFREETYPE_INCLUDE_DIRS="${CMAKE_CURRENT_SOURCE_DIR}/../../freetype/include/freetype2"
  - msbuild INSTALL.vcxproj /property:Configuration=Release 
  - set ROCKET_ROOT=%CD%/libRocket
  - cd ..

matrix:
  fast_finish: true

notifications:
- provider: Slack
  incoming_webhook: https://hooks.slack.com/services/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
  channel: '#general'
  on_build_success: true
  on_build_failure: true